### PR TITLE
[CTS] Fix event tests to use queue with profiling enabled

### LINKED ISSUE #377: `urEventGetProfilingInfo` tests should use a queue which has profiling enabled.
`urEventGetProfilingInfo` entry-point should be tested with a queue that has profiling enabled. Currently this is not the case: `urQueueTest` and `urQueueTestWithParam<T>` contain queues that do not support profiling. The flag that is required is `UR_QUEUE_FLAG_PROFILING_ENABLE`

### PR DESCRIPTION
**Pull request by veselypeta**
The event testsuite has an entrypoint `urEventGetProfilingInfo` which requires a queue that has the `UR_QUEUE_FLAG_PROFILING_ENABLE` set when it's created.

Closes #377

### CODE REVIEW

File: test/conformance/testing/include/uur/fixtures.h [hunk 1]
```diff
@@ -209,6 +209,43 @@ template <class T> struct urQueueTestWithParam : urContextTestWithParam<T> {
     ur_queue_handle_t queue;
 };
 
+struct urProfilingQueueTest : urContextTest {
+    void SetUp() override {
+        UUR_RETURN_ON_FATAL_FAILURE(urContextTest::SetUp());
+        ur_queue_property_t props[] = {UR_QUEUE_PROPERTIES_FLAGS,
+                                       UR_QUEUE_FLAG_PROFILING_ENABLE, 0};
+        urQueueCreate(this->context, this->device, props, &queue);
```
Comment (martygrant) [inline test/conformance/testing/include/uur/fixtures.h:217]: Should there be an EXPECT_SUCCESS in both of the SetUp() methods for creating the queue?

**Review by kbenzie — APPROVED** [review]
LGTM

File: test/conformance/testing/include/uur/fixtures.h (hunk 1 above)
Comment (kbenzie) [reply test/conformance/testing/include/uur/fixtures.h:217]: Good spot, I think yes.

Comment (veselypeta) [reply test/conformance/testing/include/uur/fixtures.h]: Thanks. Fixed

**Review by martygrant — APPROVED** [review]
